# Generated by Django 5.0.3 on 2024-05-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0002_rename_empud_employee_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('srank', models.IntegerField()),
            ],
        ),
    ]
